# Generated by Django 5.2.7 on 2025-11-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_revolution', '0002_remove_contactmessage_company_contactmessage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='telephone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
