# Generated by Django 5.2.7 on 2025-11-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_revolution', '0003_contactmessage_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.TextField(),
        ),
    ]
